# Generated by Django 4.2.7 on 2025-11-02 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(max_length=20, unique=True, verbose_name="学号"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("O", "其他")],
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="联系电话"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                (
                    "major",
                    models.CharField(blank=True, max_length=100, verbose_name="专业"),
                ),
                (
                    "grade",
                    models.CharField(blank=True, max_length=20, verbose_name="年级"),
                ),
                (
                    "class_name",
                    models.CharField(blank=True, max_length=50, verbose_name="班级"),
                ),
                (
                    "enrollment_date",
                    models.DateField(blank=True, null=True, verbose_name="入学日期"),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=20, verbose_name="状态"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
                "ordering": ["-created_at"],
            },
        ),
    ]
